# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 3.80.159.108
  become: yes

  tasks:

- name: Call Roles
  hosts: servers
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
